[[cells]]
name = "sudt_rce"
enable_type_id = true
location = { file = "../build/xudt_rce" }
#
# # reference to on-chain cells
# [[cells]]
# name = "genesis_cell"
# enable_type_id = false
# location = { tx_hash = "0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c", index = 0 }


# # Dep group cells
# [[dep_groups]]
# name = "my_dep_group"
# cells = [
#   "my_cell",
#   "genesis_cell"
# ]

# # Replace with your own lock if you want to unlock deployed cells.
# # For example the secp256k1 lock
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x9750c176e52911de7f058b3983e8cd73628069db"
hash_type = "type"

